//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odawa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string commentaire { get; set; }
        public int idUtilisateur { get; set; }
        public int idRestaurant { get; set; }
    
        public virtual restaurant restaurant { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
