//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odawa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public System.DateTime date { get; set; }
        public bool typeService { get; set; }
        public int nbPersonnes { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int idRestaurant { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
